// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	FIREBASE_APIKEY: string;
	FIREBASE_AUTHDOMAIN: string;
	FIREBASE_PROJECTID: string;
	FIREBASE_STORAGEBUCKET: string;
	FIREBASE_MESSAGINGSENDERID: string;
	FIREBASE_APPID: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
}
