// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_REFRESH_TOKEN: string;
	CALENDAR_ID: string;
	FIREBASE_APIKEY: string;
	FIREBASE_AUTHDOMAIN: string;
	FIREBASE_PROJECTID: string;
	FIREBASE_STORAGEBUCKET: string;
	FIREBASE_MESSAGINGSENDERID: string;
	FIREBASE_APPID: string;
}
